### PR TITLE
SSH Keys Instructions

### PR DESCRIPTION
**Pull request by cleverington**
Walkthrough for creating a GitHub Account, Creating an SSH Key, and Adding the SSH Key to GitHub.

### CODE REVIEW

**Comment by ccjjmartin** [comment]
@cleverington: Wow I just had a chance to look at this, this looks like a decent amount of work.  Thanks for the contribution.  Now I just need to learn how I pull this down locally to take a look ...

**Comment by cleverington** [comment]
I have no idea. :-D   But you could always look on my Fork:  https://github.com/cleverington/setup.environment  It is under 'instructions'. I figured you could just add a link on the README.md page to each instruction.

**Comment by ccjjmartin** [comment]
@cleverington: I found this article (https://help.github.com/articles/checking-out-pull-requests-locally/) which hopefully will do it.  If not the files changed tab appears to cover what changes were made and your fork is also an option.  I am adding a CHANGELOG.txt file right now and going to tag where the first talk was given, then figure how to pull this down locally.  Looks like we have 4 forks so hopefully, others contribute back too.

**Comment by cleverington** [comment]
Off-hand, you'll need to do a 'git remote add charles-fork xxxx', then 'git pull charles-fork master', then fix the merge-conflicts, then 'git push origin'.

I'm not sure if that is the _official_ method, but I know it works.  hehe

**Comment by ccjjmartin** [comment]
You are pretty close to the official method.  Learned something new here, I have never seen this before but next to merge pull request is a link with "command line instructions":

screen shot 2016-06-18 at 5 54 15 pm

**Comment by ccjjmartin** [comment]
I doubt GitHubs ability to track this properly in regards to closing the pull request ... Probably will pull it down check out the changes and merge up here on GitHub.

**Comment by ccjjmartin** [comment]
@cleverington: The images in step 1 are showing broken links.

**Comment by ccjjmartin** [comment]
Here is a patch for the ones I could fix.  I think we might be missing one image:

[setup.environment-cleverington.txt](https://github.com/ccjjmartin/setup.environment/files/322032/setup.environment-cleverington.txt)

**Comment by ccjjmartin** [comment]
@cleverington: I am looking at this project today and writing a blog post about it.  Any chance you can look into the missing images?

**Comment by cleverington** [comment]
Later this evening, yes.

Shouldn't take too long. The images are THERE, the links are just wrong.

I'll touch via Slack.

**Comment by cleverington** [comment]
There was some weirdness with changing between branch and master, so it ended up with two new commits.  However, the images are updated and the missing image is loaded.

**Comment by ccjjmartin** [comment]
Made some changes but since I can't commit to your fork I am going to merge this and then commit my changes.  Feel free to check them out.

**Pull request merged**
